appName: mocha # This value was modified by the initial-setup python script

service: frontend

host: a9e19b8d1dd604b6c90c36291b4190ef-1938623916.us-east-2.elb.amazonaws.com # This value was modified by the deploy-argocd pipeline

port: 80

deployment:
  labels: {    
    istio: monitor
  }
  image:
    repository: tferrari92/mocha-frontend # This value was modified by the initial-setup python script

configmap:
  images: |-
    var images = [
        "https://i.imgur.com/2Z8qEvC.png",
        "https://i.imgur.com/2Xntz2P.jpg",
        "https://i.imgur.com/pIGcI2d.jpg",
        "https://i.imgur.com/n5lNz3z.jpg",
        "https://i.imgur.com/tup8Ocu.jpg",
        "https://i.imgur.com/yjpOvlM.jpg",
        "https://i.imgur.com/akNhnrh.jpg",
        "https://i.imgur.com/eqpDlh5.jpg",
        "https://i.imgur.com/ARqnwlQ.jpg",
        "https://i.imgur.com/2lJ6xLl.jpg",
        "https://i.imgur.com/kGQUUTw.jpg",
        "https://i.imgur.com/o4LuRu7.jpg",
        "https://i.imgur.com/CnDPSpV.png",
        "https://i.imgur.com/E0s8TW6.png",
        "https://i.imgur.com/xSmJv0k.png"
    ];

ingress:
  annotations: {    
    kubernetes.io/ingress.class: alb,
    alb.ingress.kubernetes.io/scheme: internet-facing,
    alb.ingress.kubernetes.io/target-type: ip,
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP,
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port,
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15',
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5',
    alb.ingress.kubernetes.io/success-codes: '200',
    alb.ingress.kubernetes.io/healthy-threshold-count: '2',
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  }
