global:
  istioNamespace: service-mesh

meshConfig:
  ingressService: istio-gateway
  ingressSelector: gateway
  
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY # Default is ALLOW_ANY. With REGISTRY_ONLY Istio proxy blocks any host without an HTTP service or service entry defined within the mesh.
