global:
  istioNamespace: service-mesh
  proxy:
    # istio egress capture allowlist
    # https://istio.io/docs/tasks/traffic-management/egress.html#calling-external-services-directly
    # example: includeIPRanges: "172.30.0.0/16,172.20.0.0/16"
    # would only capture egress traffic on those two IP Ranges, all other outbound traffic would
    # be allowed by the sidecar
    includeIPRanges: ""
    excludeIPRanges: "*"
    includeOutboundPorts: ""
    excludeOutboundPorts: ""

meshConfig:
  ingressService: istio-gateway
  ingressSelector: gateway
