{{ if .Values.cr.create }}
---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  {{- if .Values.watchNamespace }}
  namespace: {{ .Values.watchNamespace }}
  {{- else if .Values.cr.namespace }}
  namespace: {{ .Values.cr.namespace }}
  {{- end }}
  name: {{ .Values.cr.name }}
  labels:
  {{- include "kiali-operator.labels" . | nindent 4 }}
  annotations:
    ansible.sdk.operatorframework.io/verbosity: {{ .Values.debug.verbosity | quote }}
    {{- if .Values.cr.annotations }}
    {{- toYaml .Values.cr.annotations | nindent 4 }}
    {{- end }}
spec:
  # external_services:
  #   prometheus:
  #     url: "http://kube-prometheus-stack.observability:9090/"
  #   grafana:
  #     enabled: true
  #     in_cluster_url: 'http://grafana.observability:3000/'
  {{- toYaml .Values.cr.spec | nindent 2 }}
...
{{ end }}
