# apiVersion: networking.istio.io/v1beta1
# kind: ServiceEntry
# metadata:
#   name: external-elasticsearch-com
# spec:
#   hosts:
#   - master.mocha-dev-elascache-rep-group.u0khnz.use2.cache.amazonaws.com
#   ports:
#   - number: 6379
#     name: tcp-redis
#     protocol: TCP
#   resolution: DNS
#   location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-google-com
spec:
  hosts:
  - google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
