environment: stage

deployment:
  image:
    tag: 750
  replicas: 1
  env:
    redis_host: mocha-stage-elascache-rep-group.u0khnz.ng.0001.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

secret:
  redis_pass: automate-all-the-things-stage
