---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging-cluster-issuer
spec:
  acme:
    # Staging Environment: must be used for testing before using prod env
    # Letsencrypt has a strict rate limit.
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-cluster-issuer
    solvers:
      - selector: {}
        http01:
          ingress:
            class: istio
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: production-cluster-issuer
    solvers:
      - selector: {}
        http01:
          ingress:
            class: istio  
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mocha-dev-tferrari-com
  namespace: service-mesh
spec:
  secretName: mocha-dev-tferrari-com-crt
  dnsNames:
    - mocha-dev.tferrari.com
  issuerRef:
    name: production-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
