apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.appName }}-{{ .Values.service }}-{{ .Values.environment }}-gateway
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: {{ .Values.port }}
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.host }} # Istio Gateway service external IP
