apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.appName }}-{{ .Values.environment }}-gateway
  # namespace: mocha-dev
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.appName }}-{{ .Values.environment }}.tferrari.com # Istio Gateway service external IP
    # - port:
    #     number: 443
    #     name: https
    #     protocol: HTTPS
    #   hosts:
    #     - mocha-dev.tferrari.com
    #   tls:
    #     credentialName: mocha-dev-tferrari-com-crt
    #     mode: SIMPLE
