apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-service
  namespace: observability
  labels:
    release: kube-prometheus-stack # Required to be scraped by Prometheus server
spec:
  namespaceSelector:
    matchNames:
      - service-mesh
  selector:
    matchLabels:
      app: gateway # Label of the service
  endpoints:
    - port: metrics
      path: stats/prometheus
