apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging-cluster-issuer
spec:
  acme:
    # Let’s Encrypt has a strict rate limit on certificates issued, so we use the Staging Let’s Encrypt server for testing, and then we switch to the Production Let’s Encrypt server.
    # Staging Let’s Encrypt server
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Reference to Staging secret
      name: staging-cluster-issuer
    solvers:
      - selector: {}
        http01:
          ingress:
            class: istio
