environment: dev

deployment:
  image:
    tag: 774
  replicas: 1

# AGREGAR ACA Q SE ACTUALIZE AUTOMATICAMENTE
host: http://a97ca5c4d3d2640c097734606cb29c3d-603760543.us-east-2.elb.amazonaws.com/ # This value was modified by the deploy-infra pipeline

configmap: 
  nginxConf: |-
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
    
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    
        location /api {
            # Now that we use Istio, we need to specify the http version to 1.1 for it to work (https://www.reddit.com/r/devops/comments/k0ooaw/envoy_426_http_issue/)
            proxy_http_version 1.1;
        
            proxy_pass http://mocha-backend-dev-deployment:3000/; # This value was modified by the initial-setup python script
        }
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
