# From my understanding, this should only be required when the meshConfig.outboundTrafficPolicy.mode in Istiod values is set to REGISTRY_ONLY
# But apparently it's necessary to connect to external ElastiCache even if meshConfig.outboundTrafficPolicy.mode is set to ALLOW_ANY, I don't understand why...
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ .Values.environment }}-elasticache-serviceentry
spec:
  hosts:
  - {{ .Values.redis_host }}
  ports:
  - number: 6379
    name: https
    protocol: HTTPS # With TCP it does't work because it affects all outgoing traffic, also those URLs which are not in the entry (https://github.com/istio/istio/issues/29992)
  location: MESH_EXTERNAL
  resolution: DNS
